/**
 * This file is generated by running `pnpm --filter wellness-api gen:db-type`.
 * It is checked into source control so consumers get up-to-date typings.
 * Do not edit manually.
 */

import type { ColumnType } from 'kysely';

type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I, U>
	: ColumnType<T, T | undefined, T | undefined>;

type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
	id: Generated<number>;
	email: string;
	name: string;
	created_at: Generated<Timestamp>;
	updated_at: Generated<Timestamp>;
}

export interface WellnessActivities {
	id: Generated<number>;
	user_id: number;
	activity_type: string;
	title: string;
	description: string | null;
	duration_minutes: number | null;
	completed_at: Timestamp | null;
	created_at: Generated<Timestamp>;
	updated_at: Generated<Timestamp>;
}

export interface DB {
	users: Users;
	wellness_activities: WellnessActivities;
}
